[package]
name = "milstian-http"
version = "0.1.9"
authors = ["Christian Johansson <christian@cvj.se>"]
description = "A binary HTTP parser."
license = "GPL-3.0-only"
repository = "https://github.com/cjohansson/milstian-http"

[dependencies]
